- name: Setup home config files
  copy:
    src: "{{ item.src }}"
    dest: "/home/{{ main_user.name }}/"
    owner: "{{ main_user.name }}"
    group: users
  loop:
    - { src: "home/.xinitrc" }
    - { src: "home/.Xresources" }
