 - name: install common packages
   ansible.builtin.include_tasks:
     file: "common.yml"

 - name: install aur packages
   ansible.builtin.include_tasks:
     file: "aur.yml"

 - name: install docker
   ansible.builtin.include_tasks:
     file: "docker.yml"
